apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: canary-release-analysis
spec:
  args:
    - name: latest-hash
  metrics:
    - name: hello-world-latency
      initialDelay: 5s
      interval: 1s
      failureLimit: 1
      inconclusiveLimit: 20 # allow up to 20 seconds with no metrics
      # -1 = no metric yet, OK if <= 1s (p99), fail if > 1s.
      successCondition: result[0] >= 0 && result[0] <= 1
      failureCondition: result[0] > 1
      provider:
        prometheus:
          address: http://prometheus.default.svc:9090
          query: |
            (
              histogram_quantile(
                0.99,
                sum by (le) (
                  rate(
                    http_server_requests_seconds_bucket{
                      uri="/hello-world",
                      pod=~"demo-{{args.latest-hash}}-.*"
                    }[30s]
                  )
                )
              )
            ) or vector(-1)
