apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo
  labels:
    app: demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
      annotations:
        demo/restartedAt: init
    spec:
      nodeSelector:
        role: app
      containers:
        - name: demo
          image: demo:v1
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 512Mi
  strategy:
    canary:
      abortScaleDownDelaySeconds: 0
      canaryService: demo-canary
      stableService: demo-stable
      steps:
        - setWeight: 20
        - analysis:
            templates:
              - templateName: canary-release-analysis
            args:
              - name: latest-hash
                valueFrom:
                  podTemplateHashValue: Latest
        - setWeight: 100
